# This is a basic workflow to help you get started with Actions

name: Build datapack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Commit identity theft
        run: |
          git config -g user.name CommandGeek
          git config -g user.email nathan.kulzer@protonmail.com
      
      - name: Make a branch for the box
        run: git branch -f pack main
      
      - name: Put the box on the branch
        run: git 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Delete existing data
        run: rm -rf data pack.mcmeta
      
      - name: Create pack.mcmeta
        run: echo '{"pack":{"pack_version":7,"description":"{\"text\":\"'"${cat .github/description}"'\",\"color\":\"light_purple\"}}}' > pack.mcmeta
        
      - name: Put the things in the place
        run: git add -a
      
      - name: Put the place in the box
        run: git commit -m "Build datapack"
        
      - name: Put the box on the internet
        run: git push -fuorigin pack
      
      
